language: go

go:
  - 1.12.x

env:
- GO111MODULE=on

sudo: required

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls
  - wget https://releases.hashicorp.com/terraform/0.11.13/terraform_0.11.13_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

install:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
      make install;
    fi

before_script:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
      make full-test;
      make fmtcheck;
    fi

script:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
      curl -sL https://git.io/goreleaser | bash;
    fi
  
after_success:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
      make coveralls;
    fi

notifications:
  email: false
