language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

sudo: required

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls
  - wget https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip -d /usr/local/bin/ /tmp/terraform.zip

install:
  - make install

before_script:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
    make full-test;
    else
    make test;
    fi
  - make fmtcheck

script:
  - if [ "${TRAVIS_TAG::1}" = "v" ]; then
    curl -sL https://git.io/goreleaser | bash;
    fi

after_success:
  - make coveralls

notifications:
  email: false
