name: Build
on:
  push:
    branches:
      - master
    tags:
      - "*"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/0.12.19/terraform_0.12.19_linux_amd64.zip -O /tmp/terraform.zip
          sudo unzip -o -d /usr/local/bin/ /tmp/terraform.zip

      - name: Run static checks
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          make static

      - name: Run full tests on releases
        if: github.ref != 'refs/heads/master'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make full-test

      - name: Run tests
        if: github.ref == 'refs/heads/master'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          make codecov

      - name: Build tag
        if: github.ref != 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sL https://git.io/goreleaser | bash;
